import Vue from 'vue';

import Col from './Col';
import Row from './Row';
import Input from './Input';
import InputNumber from './Input/InputNumber';
import Button from './Button';
import ButtonGroup from './Button/ButtonGroup';
import Modal from './Modal';
import Select from './Select';
import Checkbox from './Checkbox';
import Switch from './Switch';
import Tabs from './Tabs';
import Textarea from './Textarea';
import Upload from './Upload';
import ColorPicker from './ColorPicker';
import Slider from './Slider';
import Collapse from './Collapse';
import CollapseItem from './Collapse/CollapseItem';

Vue.component('BCol', Col);
Vue.component('BRow', Row);
Vue.component('BButton', Button);
Vue.component('BButtonGroup', ButtonGroup);
Vue.component('BInput', Input);
Vue.component('BInputNumber', InputNumber);
Vue.component('BModal', Modal);
Vue.component('BSelect', Select);
Vue.component('BCheckbox', Checkbox);
Vue.component('BSwitch', Switch);
Vue.component('BTabs', Tabs);
Vue.component('BTextarea', Textarea);
Vue.component('BUpload', Upload);
Vue.component('BColorPicker', ColorPicker);
Vue.component('BSlider', Slider);
Vue.component('BCollapse', Collapse);
Vue.component('BCollapseItem', CollapseItem);
